FROM node:16.17.1-alpine3.15

LABEL version="1.0"
LABEL description="Yantrayug React App"

WORKDIR /app

COPY ./package*.json ./
COPY ./yarn.lock ./

RUN yarn

COPY . .

CMD [ "yarn", "run", "start" ]