# Generated by Django 3.2.9 on 2022-10-02 11:35

import apps.profiles.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_id', models.CharField(blank=True, max_length=50, verbose_name='Employee ID')),
                ('profile_picture', models.ImageField(blank=True, default='default.jpg', upload_to=apps.profiles.models.employee_kyc_path, verbose_name="Employee's Image")),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Select', 'Select')], default='Select', max_length=20, verbose_name='Gender')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='Zip Code')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='State')),
                ('country', models.CharField(blank=True, default='India', max_length=255, verbose_name='Country')),
                ('about_me', models.TextField(blank=True, verbose_name='About Employee')),
                ('eduaction', models.CharField(blank=True, max_length=255, verbose_name='Educational Qualification')),
                ('work_experience', models.CharField(blank=True, max_length=255, verbose_name='Work Experience')),
                ('adhaar_no', models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Adhaar No')),
                ('adhaar_certificate1', models.FileField(blank=True, upload_to=apps.profiles.models.employee_kyc_path, verbose_name='Adhaar Certificate Front')),
                ('adhaar_certificate2', models.FileField(blank=True, upload_to=apps.profiles.models.employee_kyc_path, verbose_name='Adhaar Certificate Back')),
                ('pan_no', models.CharField(blank=True, max_length=20, unique=True, verbose_name='PAN No')),
                ('pan_certificate', models.FileField(blank=True, upload_to=apps.profiles.models.employee_kyc_path, verbose_name='Upload PAN')),
                ('bank_details', models.CharField(blank=True, max_length=255, verbose_name='Bank Details')),
                ('salary', models.IntegerField(blank=True, default=0, verbose_name='Salary')),
                ('is_mobile_verified', models.BooleanField(default=False, verbose_name='Mobile verified')),
                ('status', models.BooleanField(default=False, verbose_name='Employee Status')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Is Manager')),
                ('is_accountant', models.BooleanField(default=False, verbose_name='Is Accountant')),
                ('is_salesman', models.BooleanField(default=False, verbose_name='Is Salesman')),
                ('is_deliveryboy', models.BooleanField(default=False, verbose_name='Is Delivery Boy')),
                ('top_employee', models.BooleanField(default=False, verbose_name='Top Employee')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Ratings')),
                ('num_reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Reviews')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='About Customer')),
                ('profile_picture', models.ImageField(blank=True, default='default.jpg', upload_to=apps.profiles.models.customer_kyc_path, verbose_name="Customer's Image")),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Select', 'Select')], default='---', max_length=20, verbose_name='Gender')),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, default='Pune', max_length=255, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='Zip Code')),
                ('state', models.CharField(blank=True, default='Maharashtra', max_length=255, verbose_name='State')),
                ('country', models.CharField(blank=True, default='India', max_length=255, verbose_name='Country')),
                ('business_name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Business Name')),
                ('business_wano', models.CharField(blank=True, default=0, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 10 digits allowed.", regex='^\\d{9,10}$')], verbose_name='Business WhatsApp No.')),
                ('business_address_line_1', models.CharField(blank=True, max_length=255, verbose_name='Business Address Line 1')),
                ('business_address_line_2', models.CharField(blank=True, max_length=255, verbose_name='Business Address Line 2')),
                ('business_area_name', models.CharField(blank=True, max_length=64, verbose_name='Area Name')),
                ('landmark', models.CharField(blank=True, max_length=64, null=True, verbose_name='Land Mark')),
                ('directions_to_reach', models.TextField(blank=True, null=True, verbose_name='Direction To Reach')),
                ('latitude', models.FloatField(blank=True, default=19.214, verbose_name='Set Latitude')),
                ('longitude', models.FloatField(blank=True, default=19.214, verbose_name='Set Longitude')),
                ('biz_googlemap_link', models.CharField(blank=True, max_length=64, null=True, verbose_name='Google Map Link')),
                ('business_zip_code', models.CharField(blank=True, max_length=10, verbose_name='Zip Code')),
                ('business_city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('business_state', models.CharField(blank=True, max_length=255, verbose_name='State')),
                ('business_country', models.CharField(blank=True, default='India', max_length=255, verbose_name='Country')),
                ('about_business', models.TextField(blank=True, verbose_name='About Business')),
                ('upi_id', models.CharField(blank=True, max_length=50, verbose_name='UPI ID')),
                ('adhaar_no', models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Adhaar No')),
                ('adhaar_certificate1', models.FileField(blank=True, upload_to=apps.profiles.models.customer_kyc_path, verbose_name='Adhaar Certificate Front')),
                ('adhaar_certificate2', models.FileField(blank=True, upload_to=apps.profiles.models.customer_kyc_path, verbose_name='Adhaar Certificate Back')),
                ('gst_no', models.CharField(blank=True, max_length=20, verbose_name='GST No')),
                ('gst_certificate', models.FileField(blank=True, upload_to=apps.profiles.models.customer_kyc_path, verbose_name='Upload GST Doc.')),
                ('pan_no', models.CharField(blank=True, max_length=20, verbose_name='PAN No')),
                ('pan_certificate', models.FileField(blank=True, upload_to=apps.profiles.models.customer_kyc_path, verbose_name='Upload PAN')),
                ('security_cheque', models.FileField(blank=True, upload_to=apps.profiles.models.customer_kyc_path, verbose_name='Security Cheque')),
                ('visiting_card', models.FileField(blank=True, upload_to=apps.profiles.models.customer_kyc_path, verbose_name='Visiting Card')),
                ('bank_details', models.CharField(blank=True, max_length=255, verbose_name='Bank Details')),
                ('is_mobile_verified', models.BooleanField(default=False, verbose_name='Mobile verified')),
                ('is_verified_customer', models.BooleanField(default=False, verbose_name='Customer verified')),
                ('status', models.BooleanField(default=False, verbose_name='Customer Status')),
                ('top_customer', models.BooleanField(default=False, verbose_name='Top Customer')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Ratings')),
                ('num_reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Reviews')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
