# Generated by Django 3.2.9 on 2022-10-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_employee_pan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='business_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Business Name'),
        ),
    ]
