version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/media
        ports:
            - "8000"
        env_file:
            - .env
        depends_on:
            - postgres-db
        networks:
            - yantrayug-djreact

    postgres-db:
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/14/main
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - yantrayug-djreact

networks:
    yantrayug-djreact:
        driver: bridge

volumes:
    postgres_data:
    static_volume:
    media_volume: