# Generated by Django 3.2.9 on 2022-10-02 11:35

import apps.mydispatch.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dispatch_order_id', models.CharField(editable=False, max_length=50)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Invoice / Bill No')),
                ('party_name', models.CharField(max_length=255, verbose_name='Party / Business Name')),
                ('customer_first_name', models.CharField(blank=True, max_length=100, verbose_name='Customer First Name')),
                ('customer_last_name', models.CharField(blank=True, max_length=100, verbose_name='Customer Last Name')),
                ('customer_mobile', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 10 digits allowed.", regex='^\\d{9,10}$')], verbose_name='Mobile No')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('hs_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='HS Code')),
                ('rc_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='RC Code')),
                ('product', models.CharField(choices=[('Hero', 'Hero'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Hero + Battery', 'Hero + Battery'), ('Battery + Tyre', 'Battery + Tyre'), ('Hero + Tyre', 'Hero + Tyre'), ('Hero + Battery + Tyre', 'Hero + Battery + Tyre')], default='Select Product(s)', max_length=50, verbose_name='Select Product(s) Type')),
                ('total_price', models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Product Price')),
                ('pick_list', models.PositiveIntegerField(blank=True, default=0, verbose_name='Pick List')),
                ('bill_status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Select', max_length=255, verbose_name='Bill Status')),
                ('delivery_date', models.DateTimeField(verbose_name='Enter Delivery Date')),
                ('dispatch_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Cancel', 'Cancel')], default='Select Status', max_length=120, verbose_name='Dispatch Status')),
                ('recieved_status', models.CharField(blank=True, choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Select Status', max_length=120, verbose_name='Recieved Status')),
                ('payment_method', models.CharField(blank=True, choices=[('Payment Not Recived', 'Payment Not Recived'), ('Cash On Delivery', 'Cash On Delivery'), ('Online Mode', 'Online Mode'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Select Payment Method', max_length=100, null=True, verbose_name='Payment Mode')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='Remark')),
                ('refunded_amount', models.FloatField(default=0, verbose_name='Refunded Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('is_cancel_requested', models.BooleanField(default=False)),
                ('cancel_request_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('cancel_reason_details', models.TextField(blank=True, null=True)),
                ('cancel_request_status', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_man', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_by', to='profiles.employee', verbose_name='Delivered By')),
                ('picker_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picker_name', to='profiles.employee', verbose_name='Picker Name')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_salesman', to='profiles.employee', verbose_name='Salesman Name')),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
                'db_table': 'dispatches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchRecievedReciepts',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reciepts', models.FileField(blank=True, null=True, upload_to=apps.mydispatch.models.dispatch_fileuploads_path)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_reciepts', to='mydispatch.dispatch')),
            ],
            options={
                'verbose_name': 'Dispatch Recieved Reciept',
                'verbose_name_plural': 'Dispatch Recieved Reciepts',
                'db_table': 'dispatch_recieved_reciepts',
            },
        ),
    ]
